.align 4
handle_window_0_0:
window_wrapper 0, 0
handle_window_0_1:
window_wrapper 0, 1
handle_window_0_2:
window_wrapper 0, 2
handle_window_0_3:
window_wrapper 0, 3
handle_window_0_4:
window_wrapper 0, 4
handle_window_0_5:
window_wrapper 0, 5
handle_window_0_6:
window_wrapper 0, 6
handle_window_0_7:
window_wrapper 0, 7
handle_window_0_8:
window_wrapper 0, 8
handle_window_0_9:
window_wrapper 0, 9
handle_window_0_10:
window_wrapper 0, 10
handle_window_0_11:
window_wrapper 0, 11
handle_window_0_12:
window_wrapper 0, 12
handle_window_0_13:
window_wrapper 0, 13
handle_window_0_14:
window_wrapper 0, 14
handle_window_0_15:
window_wrapper 0, 15
handle_window_1_0:
window_wrapper 1, 0
handle_window_1_1:
window_wrapper 1, 1
handle_window_1_2:
window_wrapper 1, 2
handle_window_1_3:
window_wrapper 1, 3
handle_window_1_4:
window_wrapper 1, 4
handle_window_1_5:
window_wrapper 1, 5
handle_window_1_6:
window_wrapper 1, 6
handle_window_1_7:
window_wrapper 1, 7
handle_window_1_8:
window_wrapper 1, 8
handle_window_1_9:
window_wrapper 1, 9
handle_window_1_10:
window_wrapper 1, 10
handle_window_1_11:
window_wrapper 1, 11
handle_window_1_12:
window_wrapper 1, 12
handle_window_1_13:
window_wrapper 1, 13
handle_window_1_14:
window_wrapper 1, 14
handle_window_1_15:
window_wrapper 1, 15
handle_window_2_0:
window_wrapper 2, 0
handle_window_2_1:
window_wrapper 2, 1
handle_window_2_2:
window_wrapper 2, 2
handle_window_2_3:
window_wrapper 2, 3
handle_window_2_4:
window_wrapper 2, 4
handle_window_2_5:
window_wrapper 2, 5
handle_window_2_6:
window_wrapper 2, 6
handle_window_2_7:
window_wrapper 2, 7
handle_window_2_8:
window_wrapper 2, 8
handle_window_2_9:
window_wrapper 2, 9
handle_window_2_10:
window_wrapper 2, 10
handle_window_2_11:
window_wrapper 2, 11
handle_window_2_12:
window_wrapper 2, 12
handle_window_2_13:
window_wrapper 2, 13
handle_window_2_14:
window_wrapper 2, 14
handle_window_2_15:
window_wrapper 2, 15
handle_window_3_0:
window_wrapper 3, 0
handle_window_3_1:
window_wrapper 3, 1
handle_window_3_2:
window_wrapper 3, 2
handle_window_3_3:
window_wrapper 3, 3
handle_window_3_4:
window_wrapper 3, 4
handle_window_3_5:
window_wrapper 3, 5
handle_window_3_6:
window_wrapper 3, 6
handle_window_3_7:
window_wrapper 3, 7
handle_window_3_8:
window_wrapper 3, 8
handle_window_3_9:
window_wrapper 3, 9
handle_window_3_10:
window_wrapper 3, 10
handle_window_3_11:
window_wrapper 3, 11
handle_window_3_12:
window_wrapper 3, 12
handle_window_3_13:
window_wrapper 3, 13
handle_window_3_14:
window_wrapper 3, 14
handle_window_3_15:
window_wrapper 3, 15
handle_window_4_0:
window_wrapper 4, 0
handle_window_4_1:
window_wrapper 4, 1
handle_window_4_2:
window_wrapper 4, 2
handle_window_4_3:
window_wrapper 4, 3
handle_window_4_4:
window_wrapper 4, 4
handle_window_4_5:
window_wrapper 4, 5
handle_window_4_6:
window_wrapper 4, 6
handle_window_4_7:
window_wrapper 4, 7
handle_window_4_8:
window_wrapper 4, 8
handle_window_4_9:
window_wrapper 4, 9
handle_window_4_10:
window_wrapper 4, 10
handle_window_4_11:
window_wrapper 4, 11
handle_window_4_12:
window_wrapper 4, 12
handle_window_4_13:
window_wrapper 4, 13
handle_window_4_14:
window_wrapper 4, 14
handle_window_4_15:
window_wrapper 4, 15
handle_window_5_0:
window_wrapper 5, 0
handle_window_5_1:
window_wrapper 5, 1
handle_window_5_2:
window_wrapper 5, 2
handle_window_5_3:
window_wrapper 5, 3
handle_window_5_4:
window_wrapper 5, 4
handle_window_5_5:
window_wrapper 5, 5
handle_window_5_6:
window_wrapper 5, 6
handle_window_5_7:
window_wrapper 5, 7
handle_window_5_8:
window_wrapper 5, 8
handle_window_5_9:
window_wrapper 5, 9
handle_window_5_10:
window_wrapper 5, 10
handle_window_5_11:
window_wrapper 5, 11
handle_window_5_12:
window_wrapper 5, 12
handle_window_5_13:
window_wrapper 5, 13
handle_window_5_14:
window_wrapper 5, 14
handle_window_5_15:
window_wrapper 5, 15
handle_window_6_0:
window_wrapper 6, 0
handle_window_6_1:
window_wrapper 6, 1
handle_window_6_2:
window_wrapper 6, 2
handle_window_6_3:
window_wrapper 6, 3
handle_window_6_4:
window_wrapper 6, 4
handle_window_6_5:
window_wrapper 6, 5
handle_window_6_6:
window_wrapper 6, 6
handle_window_6_7:
window_wrapper 6, 7
handle_window_6_8:
window_wrapper 6, 8
handle_window_6_9:
window_wrapper 6, 9
handle_window_6_10:
window_wrapper 6, 10
handle_window_6_11:
window_wrapper 6, 11
handle_window_6_12:
window_wrapper 6, 12
handle_window_6_13:
window_wrapper 6, 13
handle_window_6_14:
window_wrapper 6, 14
handle_window_6_15:
window_wrapper 6, 15
handle_window_7_0:
window_wrapper 7, 0
handle_window_7_1:
window_wrapper 7, 1
handle_window_7_2:
window_wrapper 7, 2
handle_window_7_3:
window_wrapper 7, 3
handle_window_7_4:
window_wrapper 7, 4
handle_window_7_5:
window_wrapper 7, 5
handle_window_7_6:
window_wrapper 7, 6
handle_window_7_7:
window_wrapper 7, 7
handle_window_7_8:
window_wrapper 7, 8
handle_window_7_9:
window_wrapper 7, 9
handle_window_7_10:
window_wrapper 7, 10
handle_window_7_11:
window_wrapper 7, 11
handle_window_7_12:
window_wrapper 7, 12
handle_window_7_13:
window_wrapper 7, 13
handle_window_7_14:
window_wrapper 7, 14
handle_window_7_15:
window_wrapper 7, 15
handle_window_8_0:
window_wrapper 8, 0
handle_window_8_1:
window_wrapper 8, 1
handle_window_8_2:
window_wrapper 8, 2
handle_window_8_3:
window_wrapper 8, 3
handle_window_8_4:
window_wrapper 8, 4
handle_window_8_5:
window_wrapper 8, 5
handle_window_8_6:
window_wrapper 8, 6
handle_window_8_7:
window_wrapper 8, 7
handle_window_8_8:
window_wrapper 8, 8
handle_window_8_9:
window_wrapper 8, 9
handle_window_8_10:
window_wrapper 8, 10
handle_window_8_11:
window_wrapper 8, 11
handle_window_8_12:
window_wrapper 8, 12
handle_window_8_13:
window_wrapper 8, 13
handle_window_8_14:
window_wrapper 8, 14
handle_window_8_15:
window_wrapper 8, 15
handle_window_9_0:
window_wrapper 9, 0
handle_window_9_1:
window_wrapper 9, 1
handle_window_9_2:
window_wrapper 9, 2
handle_window_9_3:
window_wrapper 9, 3
handle_window_9_4:
window_wrapper 9, 4
handle_window_9_5:
window_wrapper 9, 5
handle_window_9_6:
window_wrapper 9, 6
handle_window_9_7:
window_wrapper 9, 7
handle_window_9_8:
window_wrapper 9, 8
handle_window_9_9:
window_wrapper 9, 9
handle_window_9_10:
window_wrapper 9, 10
handle_window_9_11:
window_wrapper 9, 11
handle_window_9_12:
window_wrapper 9, 12
handle_window_9_13:
window_wrapper 9, 13
handle_window_9_14:
window_wrapper 9, 14
handle_window_9_15:
window_wrapper 9, 15
handle_window_10_0:
window_wrapper 10, 0
handle_window_10_1:
window_wrapper 10, 1
handle_window_10_2:
window_wrapper 10, 2
handle_window_10_3:
window_wrapper 10, 3
handle_window_10_4:
window_wrapper 10, 4
handle_window_10_5:
window_wrapper 10, 5
handle_window_10_6:
window_wrapper 10, 6
handle_window_10_7:
window_wrapper 10, 7
handle_window_10_8:
window_wrapper 10, 8
handle_window_10_9:
window_wrapper 10, 9
handle_window_10_10:
window_wrapper 10, 10
handle_window_10_11:
window_wrapper 10, 11
handle_window_10_12:
window_wrapper 10, 12
handle_window_10_13:
window_wrapper 10, 13
handle_window_10_14:
window_wrapper 10, 14
handle_window_10_15:
window_wrapper 10, 15
handle_window_11_0:
window_wrapper 11, 0
handle_window_11_1:
window_wrapper 11, 1
handle_window_11_2:
window_wrapper 11, 2
handle_window_11_3:
window_wrapper 11, 3
handle_window_11_4:
window_wrapper 11, 4
handle_window_11_5:
window_wrapper 11, 5
handle_window_11_6:
window_wrapper 11, 6
handle_window_11_7:
window_wrapper 11, 7
handle_window_11_8:
window_wrapper 11, 8
handle_window_11_9:
window_wrapper 11, 9
handle_window_11_10:
window_wrapper 11, 10
handle_window_11_11:
window_wrapper 11, 11
handle_window_11_12:
window_wrapper 11, 12
handle_window_11_13:
window_wrapper 11, 13
handle_window_11_14:
window_wrapper 11, 14
handle_window_11_15:
window_wrapper 11, 15
handle_window_12_0:
window_wrapper 12, 0
handle_window_12_1:
window_wrapper 12, 1
handle_window_12_2:
window_wrapper 12, 2
handle_window_12_3:
window_wrapper 12, 3
handle_window_12_4:
window_wrapper 12, 4
handle_window_12_5:
window_wrapper 12, 5
handle_window_12_6:
window_wrapper 12, 6
handle_window_12_7:
window_wrapper 12, 7
handle_window_12_8:
window_wrapper 12, 8
handle_window_12_9:
window_wrapper 12, 9
handle_window_12_10:
window_wrapper 12, 10
handle_window_12_11:
window_wrapper 12, 11
handle_window_12_12:
window_wrapper 12, 12
handle_window_12_13:
window_wrapper 12, 13
handle_window_12_14:
window_wrapper 12, 14
handle_window_12_15:
window_wrapper 12, 15
handle_window_13_0:
window_wrapper 13, 0
handle_window_13_1:
window_wrapper 13, 1
handle_window_13_2:
window_wrapper 13, 2
handle_window_13_3:
window_wrapper 13, 3
handle_window_13_4:
window_wrapper 13, 4
handle_window_13_5:
window_wrapper 13, 5
handle_window_13_6:
window_wrapper 13, 6
handle_window_13_7:
window_wrapper 13, 7
handle_window_13_8:
window_wrapper 13, 8
handle_window_13_9:
window_wrapper 13, 9
handle_window_13_10:
window_wrapper 13, 10
handle_window_13_11:
window_wrapper 13, 11
handle_window_13_12:
window_wrapper 13, 12
handle_window_13_13:
window_wrapper 13, 13
handle_window_13_14:
window_wrapper 13, 14
handle_window_13_15:
window_wrapper 13, 15
handle_window_14_0:
window_wrapper 14, 0
handle_window_14_1:
window_wrapper 14, 1
handle_window_14_2:
window_wrapper 14, 2
handle_window_14_3:
window_wrapper 14, 3
handle_window_14_4:
window_wrapper 14, 4
handle_window_14_5:
window_wrapper 14, 5
handle_window_14_6:
window_wrapper 14, 6
handle_window_14_7:
window_wrapper 14, 7
handle_window_14_8:
window_wrapper 14, 8
handle_window_14_9:
window_wrapper 14, 9
handle_window_14_10:
window_wrapper 14, 10
handle_window_14_11:
window_wrapper 14, 11
handle_window_14_12:
window_wrapper 14, 12
handle_window_14_13:
window_wrapper 14, 13
handle_window_14_14:
window_wrapper 14, 14
handle_window_14_15:
window_wrapper 14, 15
handle_window_15_0:
window_wrapper 15, 0
handle_window_15_1:
window_wrapper 15, 1
handle_window_15_2:
window_wrapper 15, 2
handle_window_15_3:
window_wrapper 15, 3
handle_window_15_4:
window_wrapper 15, 4
handle_window_15_5:
window_wrapper 15, 5
handle_window_15_6:
window_wrapper 15, 6
handle_window_15_7:
window_wrapper 15, 7
handle_window_15_8:
window_wrapper 15, 8
handle_window_15_9:
window_wrapper 15, 9
handle_window_15_10:
window_wrapper 15, 10
handle_window_15_11:
window_wrapper 15, 11
handle_window_15_12:
window_wrapper 15, 12
handle_window_15_13:
window_wrapper 15, 13
handle_window_15_14:
window_wrapper 15, 14
handle_window_15_15:
window_wrapper 15, 15
.align 4
window_jump_table:
.long handle_window_0_0
.long handle_window_0_1
.long handle_window_0_2
.long handle_window_0_3
.long handle_window_0_4
.long handle_window_0_5
.long handle_window_0_6
.long handle_window_0_7
.long handle_window_0_8
.long handle_window_0_9
.long handle_window_0_10
.long handle_window_0_11
.long handle_window_0_12
.long handle_window_0_13
.long handle_window_0_14
.long handle_window_0_15
.long handle_window_1_0
.long handle_window_1_1
.long handle_window_1_2
.long handle_window_1_3
.long handle_window_1_4
.long handle_window_1_5
.long handle_window_1_6
.long handle_window_1_7
.long handle_window_1_8
.long handle_window_1_9
.long handle_window_1_10
.long handle_window_1_11
.long handle_window_1_12
.long handle_window_1_13
.long handle_window_1_14
.long handle_window_1_15
.long handle_window_2_0
.long handle_window_2_1
.long handle_window_2_2
.long handle_window_2_3
.long handle_window_2_4
.long handle_window_2_5
.long handle_window_2_6
.long handle_window_2_7
.long handle_window_2_8
.long handle_window_2_9
.long handle_window_2_10
.long handle_window_2_11
.long handle_window_2_12
.long handle_window_2_13
.long handle_window_2_14
.long handle_window_2_15
.long handle_window_3_0
.long handle_window_3_1
.long handle_window_3_2
.long handle_window_3_3
.long handle_window_3_4
.long handle_window_3_5
.long handle_window_3_6
.long handle_window_3_7
.long handle_window_3_8
.long handle_window_3_9
.long handle_window_3_10
.long handle_window_3_11
.long handle_window_3_12
.long handle_window_3_13
.long handle_window_3_14
.long handle_window_3_15
.long handle_window_4_0
.long handle_window_4_1
.long handle_window_4_2
.long handle_window_4_3
.long handle_window_4_4
.long handle_window_4_5
.long handle_window_4_6
.long handle_window_4_7
.long handle_window_4_8
.long handle_window_4_9
.long handle_window_4_10
.long handle_window_4_11
.long handle_window_4_12
.long handle_window_4_13
.long handle_window_4_14
.long handle_window_4_15
.long handle_window_5_0
.long handle_window_5_1
.long handle_window_5_2
.long handle_window_5_3
.long handle_window_5_4
.long handle_window_5_5
.long handle_window_5_6
.long handle_window_5_7
.long handle_window_5_8
.long handle_window_5_9
.long handle_window_5_10
.long handle_window_5_11
.long handle_window_5_12
.long handle_window_5_13
.long handle_window_5_14
.long handle_window_5_15
.long handle_window_6_0
.long handle_window_6_1
.long handle_window_6_2
.long handle_window_6_3
.long handle_window_6_4
.long handle_window_6_5
.long handle_window_6_6
.long handle_window_6_7
.long handle_window_6_8
.long handle_window_6_9
.long handle_window_6_10
.long handle_window_6_11
.long handle_window_6_12
.long handle_window_6_13
.long handle_window_6_14
.long handle_window_6_15
.long handle_window_7_0
.long handle_window_7_1
.long handle_window_7_2
.long handle_window_7_3
.long handle_window_7_4
.long handle_window_7_5
.long handle_window_7_6
.long handle_window_7_7
.long handle_window_7_8
.long handle_window_7_9
.long handle_window_7_10
.long handle_window_7_11
.long handle_window_7_12
.long handle_window_7_13
.long handle_window_7_14
.long handle_window_7_15
.long handle_window_8_0
.long handle_window_8_1
.long handle_window_8_2
.long handle_window_8_3
.long handle_window_8_4
.long handle_window_8_5
.long handle_window_8_6
.long handle_window_8_7
.long handle_window_8_8
.long handle_window_8_9
.long handle_window_8_10
.long handle_window_8_11
.long handle_window_8_12
.long handle_window_8_13
.long handle_window_8_14
.long handle_window_8_15
.long handle_window_9_0
.long handle_window_9_1
.long handle_window_9_2
.long handle_window_9_3
.long handle_window_9_4
.long handle_window_9_5
.long handle_window_9_6
.long handle_window_9_7
.long handle_window_9_8
.long handle_window_9_9
.long handle_window_9_10
.long handle_window_9_11
.long handle_window_9_12
.long handle_window_9_13
.long handle_window_9_14
.long handle_window_9_15
.long handle_window_10_0
.long handle_window_10_1
.long handle_window_10_2
.long handle_window_10_3
.long handle_window_10_4
.long handle_window_10_5
.long handle_window_10_6
.long handle_window_10_7
.long handle_window_10_8
.long handle_window_10_9
.long handle_window_10_10
.long handle_window_10_11
.long handle_window_10_12
.long handle_window_10_13
.long handle_window_10_14
.long handle_window_10_15
.long handle_window_11_0
.long handle_window_11_1
.long handle_window_11_2
.long handle_window_11_3
.long handle_window_11_4
.long handle_window_11_5
.long handle_window_11_6
.long handle_window_11_7
.long handle_window_11_8
.long handle_window_11_9
.long handle_window_11_10
.long handle_window_11_11
.long handle_window_11_12
.long handle_window_11_13
.long handle_window_11_14
.long handle_window_11_15
.long handle_window_12_0
.long handle_window_12_1
.long handle_window_12_2
.long handle_window_12_3
.long handle_window_12_4
.long handle_window_12_5
.long handle_window_12_6
.long handle_window_12_7
.long handle_window_12_8
.long handle_window_12_9
.long handle_window_12_10
.long handle_window_12_11
.long handle_window_12_12
.long handle_window_12_13
.long handle_window_12_14
.long handle_window_12_15
.long handle_window_13_0
.long handle_window_13_1
.long handle_window_13_2
.long handle_window_13_3
.long handle_window_13_4
.long handle_window_13_5
.long handle_window_13_6
.long handle_window_13_7
.long handle_window_13_8
.long handle_window_13_9
.long handle_window_13_10
.long handle_window_13_11
.long handle_window_13_12
.long handle_window_13_13
.long handle_window_13_14
.long handle_window_13_15
.long handle_window_14_0
.long handle_window_14_1
.long handle_window_14_2
.long handle_window_14_3
.long handle_window_14_4
.long handle_window_14_5
.long handle_window_14_6
.long handle_window_14_7
.long handle_window_14_8
.long handle_window_14_9
.long handle_window_14_10
.long handle_window_14_11
.long handle_window_14_12
.long handle_window_14_13
.long handle_window_14_14
.long handle_window_14_15
.long handle_window_15_0
.long handle_window_15_1
.long handle_window_15_2
.long handle_window_15_3
.long handle_window_15_4
.long handle_window_15_5
.long handle_window_15_6
.long handle_window_15_7
.long handle_window_15_8
.long handle_window_15_9
.long handle_window_15_10
.long handle_window_15_11
.long handle_window_15_12
.long handle_window_15_13
.long handle_window_15_14
.long handle_window_15_15
.align 4
handle_sprite_0_0_0_0:
handle_sprite handle_sprite_0_0_0_0, 0, 0, 0, 0
handle_sprite_0_0_0_1:
handle_sprite handle_sprite_0_0_0_1, 0, 0, 0, 1
handle_sprite_0_0_1_0:
handle_sprite handle_sprite_0_0_1_0, 0, 0, 1, 0
handle_sprite_0_0_1_1:
handle_sprite handle_sprite_0_0_1_1, 0, 0, 1, 1
handle_sprite_0_1_0_0:
handle_sprite handle_sprite_0_1_0_0, 0, 1, 0, 0
handle_sprite_0_1_0_1:
handle_sprite handle_sprite_0_1_0_1, 0, 1, 0, 1
handle_sprite_0_1_1_0:
handle_sprite handle_sprite_0_1_1_0, 0, 1, 1, 0
handle_sprite_0_1_1_1:
handle_sprite handle_sprite_0_1_1_1, 0, 1, 1, 1
handle_sprite_1_0_0_0:
handle_sprite handle_sprite_1_0_0_0, 1, 0, 0, 0
handle_sprite_1_0_0_1:
handle_sprite handle_sprite_1_0_0_1, 1, 0, 0, 1
handle_sprite_1_0_1_0:
handle_sprite handle_sprite_1_0_1_0, 1, 0, 1, 0
handle_sprite_1_0_1_1:
handle_sprite handle_sprite_1_0_1_1, 1, 0, 1, 1
handle_sprite_1_1_0_0:
handle_sprite handle_sprite_1_1_0_0, 1, 1, 0, 0
handle_sprite_1_1_0_1:
handle_sprite handle_sprite_1_1_0_1, 1, 1, 0, 1
handle_sprite_1_1_1_0:
handle_sprite handle_sprite_1_1_1_0, 1, 1, 1, 0
handle_sprite_1_1_1_1:
handle_sprite handle_sprite_1_1_1_1, 1, 1, 1, 1
.align 4
sprite_jump_table:
.long handle_sprite_0_0_0_0
.long handle_sprite_0_0_0_1
.long handle_sprite_0_0_1_0
.long handle_sprite_0_0_1_1
.long handle_sprite_0_1_0_0
.long handle_sprite_0_1_0_1
.long handle_sprite_0_1_1_0
.long handle_sprite_0_1_1_1
.long handle_sprite_1_0_0_0
.long handle_sprite_1_0_0_1
.long handle_sprite_1_0_1_0
.long handle_sprite_1_0_1_1
.long handle_sprite_1_1_0_0
.long handle_sprite_1_1_0_1
.long handle_sprite_1_1_1_0
.long handle_sprite_1_1_1_1
.align 4
handle_cmath_0_0_0_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_0_0_0, 0, 0, 0, 0, 0, 0, 0, 0
handle_cmath_0_0_0_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_0_0_1, 0, 0, 0, 0, 0, 0, 0, 1
handle_cmath_0_0_0_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_0_1_0, 0, 0, 0, 0, 0, 0, 1, 0
handle_cmath_0_0_0_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_0_1_1, 0, 0, 0, 0, 0, 0, 1, 1
handle_cmath_0_0_0_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_1_0_0, 0, 0, 0, 0, 0, 1, 0, 0
handle_cmath_0_0_0_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_1_0_1, 0, 0, 0, 0, 0, 1, 0, 1
handle_cmath_0_0_0_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_1_1_0, 0, 0, 0, 0, 0, 1, 1, 0
handle_cmath_0_0_0_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_0_1_1_1, 0, 0, 0, 0, 0, 1, 1, 1
handle_cmath_0_0_0_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_0_0_0, 0, 0, 0, 0, 1, 0, 0, 0
handle_cmath_0_0_0_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_0_0_1, 0, 0, 0, 0, 1, 0, 0, 1
handle_cmath_0_0_0_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_0_1_0, 0, 0, 0, 0, 1, 0, 1, 0
handle_cmath_0_0_0_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_0_1_1, 0, 0, 0, 0, 1, 0, 1, 1
handle_cmath_0_0_0_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_1_0_0, 0, 0, 0, 0, 1, 1, 0, 0
handle_cmath_0_0_0_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_1_0_1, 0, 0, 0, 0, 1, 1, 0, 1
handle_cmath_0_0_0_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_1_1_0, 0, 0, 0, 0, 1, 1, 1, 0
handle_cmath_0_0_0_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_0_1_1_1_1, 0, 0, 0, 0, 1, 1, 1, 1
handle_cmath_0_0_0_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_0_0_0, 0, 0, 0, 1, 0, 0, 0, 0
handle_cmath_0_0_0_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_0_0_1, 0, 0, 0, 1, 0, 0, 0, 1
handle_cmath_0_0_0_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_0_1_0, 0, 0, 0, 1, 0, 0, 1, 0
handle_cmath_0_0_0_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_0_1_1, 0, 0, 0, 1, 0, 0, 1, 1
handle_cmath_0_0_0_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_1_0_0, 0, 0, 0, 1, 0, 1, 0, 0
handle_cmath_0_0_0_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_1_0_1, 0, 0, 0, 1, 0, 1, 0, 1
handle_cmath_0_0_0_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_1_1_0, 0, 0, 0, 1, 0, 1, 1, 0
handle_cmath_0_0_0_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_0_1_1_1, 0, 0, 0, 1, 0, 1, 1, 1
handle_cmath_0_0_0_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_0_0_0, 0, 0, 0, 1, 1, 0, 0, 0
handle_cmath_0_0_0_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_0_0_1, 0, 0, 0, 1, 1, 0, 0, 1
handle_cmath_0_0_0_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_0_1_0, 0, 0, 0, 1, 1, 0, 1, 0
handle_cmath_0_0_0_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_0_1_1, 0, 0, 0, 1, 1, 0, 1, 1
handle_cmath_0_0_0_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_1_0_0, 0, 0, 0, 1, 1, 1, 0, 0
handle_cmath_0_0_0_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_1_0_1, 0, 0, 0, 1, 1, 1, 0, 1
handle_cmath_0_0_0_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_1_1_0, 0, 0, 0, 1, 1, 1, 1, 0
handle_cmath_0_0_0_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_0_1_1_1_1_1, 0, 0, 0, 1, 1, 1, 1, 1
handle_cmath_0_0_1_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_0_0_0, 0, 0, 1, 0, 0, 0, 0, 0
handle_cmath_0_0_1_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_0_0_1, 0, 0, 1, 0, 0, 0, 0, 1
handle_cmath_0_0_1_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_0_1_0, 0, 0, 1, 0, 0, 0, 1, 0
handle_cmath_0_0_1_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_0_1_1, 0, 0, 1, 0, 0, 0, 1, 1
handle_cmath_0_0_1_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_1_0_0, 0, 0, 1, 0, 0, 1, 0, 0
handle_cmath_0_0_1_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_1_0_1, 0, 0, 1, 0, 0, 1, 0, 1
handle_cmath_0_0_1_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_1_1_0, 0, 0, 1, 0, 0, 1, 1, 0
handle_cmath_0_0_1_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_0_1_1_1, 0, 0, 1, 0, 0, 1, 1, 1
handle_cmath_0_0_1_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_0_0_0, 0, 0, 1, 0, 1, 0, 0, 0
handle_cmath_0_0_1_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_0_0_1, 0, 0, 1, 0, 1, 0, 0, 1
handle_cmath_0_0_1_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_0_1_0, 0, 0, 1, 0, 1, 0, 1, 0
handle_cmath_0_0_1_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_0_1_1, 0, 0, 1, 0, 1, 0, 1, 1
handle_cmath_0_0_1_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_1_0_0, 0, 0, 1, 0, 1, 1, 0, 0
handle_cmath_0_0_1_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_1_0_1, 0, 0, 1, 0, 1, 1, 0, 1
handle_cmath_0_0_1_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_1_1_0, 0, 0, 1, 0, 1, 1, 1, 0
handle_cmath_0_0_1_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_0_1_1_1_1, 0, 0, 1, 0, 1, 1, 1, 1
handle_cmath_0_0_1_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_0_0_0, 0, 0, 1, 1, 0, 0, 0, 0
handle_cmath_0_0_1_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_0_0_1, 0, 0, 1, 1, 0, 0, 0, 1
handle_cmath_0_0_1_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_0_1_0, 0, 0, 1, 1, 0, 0, 1, 0
handle_cmath_0_0_1_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_0_1_1, 0, 0, 1, 1, 0, 0, 1, 1
handle_cmath_0_0_1_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_1_0_0, 0, 0, 1, 1, 0, 1, 0, 0
handle_cmath_0_0_1_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_1_0_1, 0, 0, 1, 1, 0, 1, 0, 1
handle_cmath_0_0_1_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_1_1_0, 0, 0, 1, 1, 0, 1, 1, 0
handle_cmath_0_0_1_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_0_1_1_1, 0, 0, 1, 1, 0, 1, 1, 1
handle_cmath_0_0_1_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_0_0_0, 0, 0, 1, 1, 1, 0, 0, 0
handle_cmath_0_0_1_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_0_0_1, 0, 0, 1, 1, 1, 0, 0, 1
handle_cmath_0_0_1_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_0_1_0, 0, 0, 1, 1, 1, 0, 1, 0
handle_cmath_0_0_1_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_0_1_1, 0, 0, 1, 1, 1, 0, 1, 1
handle_cmath_0_0_1_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_1_0_0, 0, 0, 1, 1, 1, 1, 0, 0
handle_cmath_0_0_1_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_1_0_1, 0, 0, 1, 1, 1, 1, 0, 1
handle_cmath_0_0_1_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_1_1_0, 0, 0, 1, 1, 1, 1, 1, 0
handle_cmath_0_0_1_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_0_1_1_1_1_1_1, 0, 0, 1, 1, 1, 1, 1, 1
handle_cmath_0_1_0_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_0_0_0, 0, 1, 0, 0, 0, 0, 0, 0
handle_cmath_0_1_0_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_0_0_1, 0, 1, 0, 0, 0, 0, 0, 1
handle_cmath_0_1_0_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_0_1_0, 0, 1, 0, 0, 0, 0, 1, 0
handle_cmath_0_1_0_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_0_1_1, 0, 1, 0, 0, 0, 0, 1, 1
handle_cmath_0_1_0_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_1_0_0, 0, 1, 0, 0, 0, 1, 0, 0
handle_cmath_0_1_0_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_1_0_1, 0, 1, 0, 0, 0, 1, 0, 1
handle_cmath_0_1_0_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_1_1_0, 0, 1, 0, 0, 0, 1, 1, 0
handle_cmath_0_1_0_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_0_1_1_1, 0, 1, 0, 0, 0, 1, 1, 1
handle_cmath_0_1_0_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_0_0_0, 0, 1, 0, 0, 1, 0, 0, 0
handle_cmath_0_1_0_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_0_0_1, 0, 1, 0, 0, 1, 0, 0, 1
handle_cmath_0_1_0_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_0_1_0, 0, 1, 0, 0, 1, 0, 1, 0
handle_cmath_0_1_0_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_0_1_1, 0, 1, 0, 0, 1, 0, 1, 1
handle_cmath_0_1_0_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_1_0_0, 0, 1, 0, 0, 1, 1, 0, 0
handle_cmath_0_1_0_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_1_0_1, 0, 1, 0, 0, 1, 1, 0, 1
handle_cmath_0_1_0_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_1_1_0, 0, 1, 0, 0, 1, 1, 1, 0
handle_cmath_0_1_0_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_0_1_1_1_1, 0, 1, 0, 0, 1, 1, 1, 1
handle_cmath_0_1_0_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_0_0_0, 0, 1, 0, 1, 0, 0, 0, 0
handle_cmath_0_1_0_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_0_0_1, 0, 1, 0, 1, 0, 0, 0, 1
handle_cmath_0_1_0_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_0_1_0, 0, 1, 0, 1, 0, 0, 1, 0
handle_cmath_0_1_0_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_0_1_1, 0, 1, 0, 1, 0, 0, 1, 1
handle_cmath_0_1_0_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_1_0_0, 0, 1, 0, 1, 0, 1, 0, 0
handle_cmath_0_1_0_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_1_0_1, 0, 1, 0, 1, 0, 1, 0, 1
handle_cmath_0_1_0_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_1_1_0, 0, 1, 0, 1, 0, 1, 1, 0
handle_cmath_0_1_0_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_0_1_1_1, 0, 1, 0, 1, 0, 1, 1, 1
handle_cmath_0_1_0_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_0_0_0, 0, 1, 0, 1, 1, 0, 0, 0
handle_cmath_0_1_0_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_0_0_1, 0, 1, 0, 1, 1, 0, 0, 1
handle_cmath_0_1_0_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_0_1_0, 0, 1, 0, 1, 1, 0, 1, 0
handle_cmath_0_1_0_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_0_1_1, 0, 1, 0, 1, 1, 0, 1, 1
handle_cmath_0_1_0_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_1_0_0, 0, 1, 0, 1, 1, 1, 0, 0
handle_cmath_0_1_0_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_1_0_1, 0, 1, 0, 1, 1, 1, 0, 1
handle_cmath_0_1_0_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_1_1_0, 0, 1, 0, 1, 1, 1, 1, 0
handle_cmath_0_1_0_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_0_1_1_1_1_1, 0, 1, 0, 1, 1, 1, 1, 1
handle_cmath_0_1_1_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_0_0_0, 0, 1, 1, 0, 0, 0, 0, 0
handle_cmath_0_1_1_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_0_0_1, 0, 1, 1, 0, 0, 0, 0, 1
handle_cmath_0_1_1_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_0_1_0, 0, 1, 1, 0, 0, 0, 1, 0
handle_cmath_0_1_1_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_0_1_1, 0, 1, 1, 0, 0, 0, 1, 1
handle_cmath_0_1_1_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_1_0_0, 0, 1, 1, 0, 0, 1, 0, 0
handle_cmath_0_1_1_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_1_0_1, 0, 1, 1, 0, 0, 1, 0, 1
handle_cmath_0_1_1_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_1_1_0, 0, 1, 1, 0, 0, 1, 1, 0
handle_cmath_0_1_1_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_0_1_1_1, 0, 1, 1, 0, 0, 1, 1, 1
handle_cmath_0_1_1_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_0_0_0, 0, 1, 1, 0, 1, 0, 0, 0
handle_cmath_0_1_1_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_0_0_1, 0, 1, 1, 0, 1, 0, 0, 1
handle_cmath_0_1_1_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_0_1_0, 0, 1, 1, 0, 1, 0, 1, 0
handle_cmath_0_1_1_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_0_1_1, 0, 1, 1, 0, 1, 0, 1, 1
handle_cmath_0_1_1_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_1_0_0, 0, 1, 1, 0, 1, 1, 0, 0
handle_cmath_0_1_1_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_1_0_1, 0, 1, 1, 0, 1, 1, 0, 1
handle_cmath_0_1_1_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_1_1_0, 0, 1, 1, 0, 1, 1, 1, 0
handle_cmath_0_1_1_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_0_1_1_1_1, 0, 1, 1, 0, 1, 1, 1, 1
handle_cmath_0_1_1_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_0_0_0, 0, 1, 1, 1, 0, 0, 0, 0
handle_cmath_0_1_1_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_0_0_1, 0, 1, 1, 1, 0, 0, 0, 1
handle_cmath_0_1_1_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_0_1_0, 0, 1, 1, 1, 0, 0, 1, 0
handle_cmath_0_1_1_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_0_1_1, 0, 1, 1, 1, 0, 0, 1, 1
handle_cmath_0_1_1_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_1_0_0, 0, 1, 1, 1, 0, 1, 0, 0
handle_cmath_0_1_1_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_1_0_1, 0, 1, 1, 1, 0, 1, 0, 1
handle_cmath_0_1_1_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_1_1_0, 0, 1, 1, 1, 0, 1, 1, 0
handle_cmath_0_1_1_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_0_1_1_1, 0, 1, 1, 1, 0, 1, 1, 1
handle_cmath_0_1_1_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_0_0_0, 0, 1, 1, 1, 1, 0, 0, 0
handle_cmath_0_1_1_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_0_0_1, 0, 1, 1, 1, 1, 0, 0, 1
handle_cmath_0_1_1_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_0_1_0, 0, 1, 1, 1, 1, 0, 1, 0
handle_cmath_0_1_1_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_0_1_1, 0, 1, 1, 1, 1, 0, 1, 1
handle_cmath_0_1_1_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_1_0_0, 0, 1, 1, 1, 1, 1, 0, 0
handle_cmath_0_1_1_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_1_0_1, 0, 1, 1, 1, 1, 1, 0, 1
handle_cmath_0_1_1_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_1_1_0, 0, 1, 1, 1, 1, 1, 1, 0
handle_cmath_0_1_1_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_0_1_1_1_1_1_1_1, 0, 1, 1, 1, 1, 1, 1, 1
handle_cmath_1_0_0_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_0_0_0, 1, 0, 0, 0, 0, 0, 0, 0
handle_cmath_1_0_0_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_0_0_1, 1, 0, 0, 0, 0, 0, 0, 1
handle_cmath_1_0_0_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_0_1_0, 1, 0, 0, 0, 0, 0, 1, 0
handle_cmath_1_0_0_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_0_1_1, 1, 0, 0, 0, 0, 0, 1, 1
handle_cmath_1_0_0_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_1_0_0, 1, 0, 0, 0, 0, 1, 0, 0
handle_cmath_1_0_0_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_1_0_1, 1, 0, 0, 0, 0, 1, 0, 1
handle_cmath_1_0_0_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_1_1_0, 1, 0, 0, 0, 0, 1, 1, 0
handle_cmath_1_0_0_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_0_1_1_1, 1, 0, 0, 0, 0, 1, 1, 1
handle_cmath_1_0_0_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_0_0_0, 1, 0, 0, 0, 1, 0, 0, 0
handle_cmath_1_0_0_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_0_0_1, 1, 0, 0, 0, 1, 0, 0, 1
handle_cmath_1_0_0_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_0_1_0, 1, 0, 0, 0, 1, 0, 1, 0
handle_cmath_1_0_0_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_0_1_1, 1, 0, 0, 0, 1, 0, 1, 1
handle_cmath_1_0_0_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_1_0_0, 1, 0, 0, 0, 1, 1, 0, 0
handle_cmath_1_0_0_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_1_0_1, 1, 0, 0, 0, 1, 1, 0, 1
handle_cmath_1_0_0_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_1_1_0, 1, 0, 0, 0, 1, 1, 1, 0
handle_cmath_1_0_0_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_0_1_1_1_1, 1, 0, 0, 0, 1, 1, 1, 1
handle_cmath_1_0_0_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_0_0_0, 1, 0, 0, 1, 0, 0, 0, 0
handle_cmath_1_0_0_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_0_0_1, 1, 0, 0, 1, 0, 0, 0, 1
handle_cmath_1_0_0_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_0_1_0, 1, 0, 0, 1, 0, 0, 1, 0
handle_cmath_1_0_0_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_0_1_1, 1, 0, 0, 1, 0, 0, 1, 1
handle_cmath_1_0_0_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_1_0_0, 1, 0, 0, 1, 0, 1, 0, 0
handle_cmath_1_0_0_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_1_0_1, 1, 0, 0, 1, 0, 1, 0, 1
handle_cmath_1_0_0_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_1_1_0, 1, 0, 0, 1, 0, 1, 1, 0
handle_cmath_1_0_0_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_0_1_1_1, 1, 0, 0, 1, 0, 1, 1, 1
handle_cmath_1_0_0_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_0_0_0, 1, 0, 0, 1, 1, 0, 0, 0
handle_cmath_1_0_0_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_0_0_1, 1, 0, 0, 1, 1, 0, 0, 1
handle_cmath_1_0_0_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_0_1_0, 1, 0, 0, 1, 1, 0, 1, 0
handle_cmath_1_0_0_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_0_1_1, 1, 0, 0, 1, 1, 0, 1, 1
handle_cmath_1_0_0_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_1_0_0, 1, 0, 0, 1, 1, 1, 0, 0
handle_cmath_1_0_0_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_1_0_1, 1, 0, 0, 1, 1, 1, 0, 1
handle_cmath_1_0_0_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_1_1_0, 1, 0, 0, 1, 1, 1, 1, 0
handle_cmath_1_0_0_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_0_1_1_1_1_1, 1, 0, 0, 1, 1, 1, 1, 1
handle_cmath_1_0_1_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_0_0_0, 1, 0, 1, 0, 0, 0, 0, 0
handle_cmath_1_0_1_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_0_0_1, 1, 0, 1, 0, 0, 0, 0, 1
handle_cmath_1_0_1_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_0_1_0, 1, 0, 1, 0, 0, 0, 1, 0
handle_cmath_1_0_1_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_0_1_1, 1, 0, 1, 0, 0, 0, 1, 1
handle_cmath_1_0_1_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_1_0_0, 1, 0, 1, 0, 0, 1, 0, 0
handle_cmath_1_0_1_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_1_0_1, 1, 0, 1, 0, 0, 1, 0, 1
handle_cmath_1_0_1_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_1_1_0, 1, 0, 1, 0, 0, 1, 1, 0
handle_cmath_1_0_1_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_0_1_1_1, 1, 0, 1, 0, 0, 1, 1, 1
handle_cmath_1_0_1_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_0_0_0, 1, 0, 1, 0, 1, 0, 0, 0
handle_cmath_1_0_1_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_0_0_1, 1, 0, 1, 0, 1, 0, 0, 1
handle_cmath_1_0_1_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_0_1_0, 1, 0, 1, 0, 1, 0, 1, 0
handle_cmath_1_0_1_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_0_1_1, 1, 0, 1, 0, 1, 0, 1, 1
handle_cmath_1_0_1_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_1_0_0, 1, 0, 1, 0, 1, 1, 0, 0
handle_cmath_1_0_1_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_1_0_1, 1, 0, 1, 0, 1, 1, 0, 1
handle_cmath_1_0_1_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_1_1_0, 1, 0, 1, 0, 1, 1, 1, 0
handle_cmath_1_0_1_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_0_1_1_1_1, 1, 0, 1, 0, 1, 1, 1, 1
handle_cmath_1_0_1_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_0_0_0, 1, 0, 1, 1, 0, 0, 0, 0
handle_cmath_1_0_1_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_0_0_1, 1, 0, 1, 1, 0, 0, 0, 1
handle_cmath_1_0_1_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_0_1_0, 1, 0, 1, 1, 0, 0, 1, 0
handle_cmath_1_0_1_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_0_1_1, 1, 0, 1, 1, 0, 0, 1, 1
handle_cmath_1_0_1_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_1_0_0, 1, 0, 1, 1, 0, 1, 0, 0
handle_cmath_1_0_1_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_1_0_1, 1, 0, 1, 1, 0, 1, 0, 1
handle_cmath_1_0_1_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_1_1_0, 1, 0, 1, 1, 0, 1, 1, 0
handle_cmath_1_0_1_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_0_1_1_1, 1, 0, 1, 1, 0, 1, 1, 1
handle_cmath_1_0_1_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_0_0_0, 1, 0, 1, 1, 1, 0, 0, 0
handle_cmath_1_0_1_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_0_0_1, 1, 0, 1, 1, 1, 0, 0, 1
handle_cmath_1_0_1_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_0_1_0, 1, 0, 1, 1, 1, 0, 1, 0
handle_cmath_1_0_1_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_0_1_1, 1, 0, 1, 1, 1, 0, 1, 1
handle_cmath_1_0_1_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_1_0_0, 1, 0, 1, 1, 1, 1, 0, 0
handle_cmath_1_0_1_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_1_0_1, 1, 0, 1, 1, 1, 1, 0, 1
handle_cmath_1_0_1_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_1_1_0, 1, 0, 1, 1, 1, 1, 1, 0
handle_cmath_1_0_1_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_0_1_1_1_1_1_1, 1, 0, 1, 1, 1, 1, 1, 1
handle_cmath_1_1_0_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_0_0_0, 1, 1, 0, 0, 0, 0, 0, 0
handle_cmath_1_1_0_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_0_0_1, 1, 1, 0, 0, 0, 0, 0, 1
handle_cmath_1_1_0_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_0_1_0, 1, 1, 0, 0, 0, 0, 1, 0
handle_cmath_1_1_0_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_0_1_1, 1, 1, 0, 0, 0, 0, 1, 1
handle_cmath_1_1_0_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_1_0_0, 1, 1, 0, 0, 0, 1, 0, 0
handle_cmath_1_1_0_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_1_0_1, 1, 1, 0, 0, 0, 1, 0, 1
handle_cmath_1_1_0_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_1_1_0, 1, 1, 0, 0, 0, 1, 1, 0
handle_cmath_1_1_0_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_0_1_1_1, 1, 1, 0, 0, 0, 1, 1, 1
handle_cmath_1_1_0_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_0_0_0, 1, 1, 0, 0, 1, 0, 0, 0
handle_cmath_1_1_0_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_0_0_1, 1, 1, 0, 0, 1, 0, 0, 1
handle_cmath_1_1_0_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_0_1_0, 1, 1, 0, 0, 1, 0, 1, 0
handle_cmath_1_1_0_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_0_1_1, 1, 1, 0, 0, 1, 0, 1, 1
handle_cmath_1_1_0_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_1_0_0, 1, 1, 0, 0, 1, 1, 0, 0
handle_cmath_1_1_0_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_1_0_1, 1, 1, 0, 0, 1, 1, 0, 1
handle_cmath_1_1_0_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_1_1_0, 1, 1, 0, 0, 1, 1, 1, 0
handle_cmath_1_1_0_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_0_1_1_1_1, 1, 1, 0, 0, 1, 1, 1, 1
handle_cmath_1_1_0_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_0_0_0, 1, 1, 0, 1, 0, 0, 0, 0
handle_cmath_1_1_0_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_0_0_1, 1, 1, 0, 1, 0, 0, 0, 1
handle_cmath_1_1_0_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_0_1_0, 1, 1, 0, 1, 0, 0, 1, 0
handle_cmath_1_1_0_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_0_1_1, 1, 1, 0, 1, 0, 0, 1, 1
handle_cmath_1_1_0_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_1_0_0, 1, 1, 0, 1, 0, 1, 0, 0
handle_cmath_1_1_0_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_1_0_1, 1, 1, 0, 1, 0, 1, 0, 1
handle_cmath_1_1_0_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_1_1_0, 1, 1, 0, 1, 0, 1, 1, 0
handle_cmath_1_1_0_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_0_1_1_1, 1, 1, 0, 1, 0, 1, 1, 1
handle_cmath_1_1_0_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_0_0_0, 1, 1, 0, 1, 1, 0, 0, 0
handle_cmath_1_1_0_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_0_0_1, 1, 1, 0, 1, 1, 0, 0, 1
handle_cmath_1_1_0_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_0_1_0, 1, 1, 0, 1, 1, 0, 1, 0
handle_cmath_1_1_0_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_0_1_1, 1, 1, 0, 1, 1, 0, 1, 1
handle_cmath_1_1_0_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_1_0_0, 1, 1, 0, 1, 1, 1, 0, 0
handle_cmath_1_1_0_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_1_0_1, 1, 1, 0, 1, 1, 1, 0, 1
handle_cmath_1_1_0_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_1_1_0, 1, 1, 0, 1, 1, 1, 1, 0
handle_cmath_1_1_0_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_0_1_1_1_1_1, 1, 1, 0, 1, 1, 1, 1, 1
handle_cmath_1_1_1_0_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_0_0_0, 1, 1, 1, 0, 0, 0, 0, 0
handle_cmath_1_1_1_0_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_0_0_1, 1, 1, 1, 0, 0, 0, 0, 1
handle_cmath_1_1_1_0_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_0_1_0, 1, 1, 1, 0, 0, 0, 1, 0
handle_cmath_1_1_1_0_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_0_1_1, 1, 1, 1, 0, 0, 0, 1, 1
handle_cmath_1_1_1_0_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_1_0_0, 1, 1, 1, 0, 0, 1, 0, 0
handle_cmath_1_1_1_0_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_1_0_1, 1, 1, 1, 0, 0, 1, 0, 1
handle_cmath_1_1_1_0_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_1_1_0, 1, 1, 1, 0, 0, 1, 1, 0
handle_cmath_1_1_1_0_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_0_1_1_1, 1, 1, 1, 0, 0, 1, 1, 1
handle_cmath_1_1_1_0_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_0_0_0, 1, 1, 1, 0, 1, 0, 0, 0
handle_cmath_1_1_1_0_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_0_0_1, 1, 1, 1, 0, 1, 0, 0, 1
handle_cmath_1_1_1_0_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_0_1_0, 1, 1, 1, 0, 1, 0, 1, 0
handle_cmath_1_1_1_0_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_0_1_1, 1, 1, 1, 0, 1, 0, 1, 1
handle_cmath_1_1_1_0_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_1_0_0, 1, 1, 1, 0, 1, 1, 0, 0
handle_cmath_1_1_1_0_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_1_0_1, 1, 1, 1, 0, 1, 1, 0, 1
handle_cmath_1_1_1_0_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_1_1_0, 1, 1, 1, 0, 1, 1, 1, 0
handle_cmath_1_1_1_0_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_0_1_1_1_1, 1, 1, 1, 0, 1, 1, 1, 1
handle_cmath_1_1_1_1_0_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_0_0_0, 1, 1, 1, 1, 0, 0, 0, 0
handle_cmath_1_1_1_1_0_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_0_0_1, 1, 1, 1, 1, 0, 0, 0, 1
handle_cmath_1_1_1_1_0_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_0_1_0, 1, 1, 1, 1, 0, 0, 1, 0
handle_cmath_1_1_1_1_0_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_0_1_1, 1, 1, 1, 1, 0, 0, 1, 1
handle_cmath_1_1_1_1_0_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_1_0_0, 1, 1, 1, 1, 0, 1, 0, 0
handle_cmath_1_1_1_1_0_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_1_0_1, 1, 1, 1, 1, 0, 1, 0, 1
handle_cmath_1_1_1_1_0_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_1_1_0, 1, 1, 1, 1, 0, 1, 1, 0
handle_cmath_1_1_1_1_0_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_0_1_1_1, 1, 1, 1, 1, 0, 1, 1, 1
handle_cmath_1_1_1_1_1_0_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_0_0_0, 1, 1, 1, 1, 1, 0, 0, 0
handle_cmath_1_1_1_1_1_0_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_0_0_1, 1, 1, 1, 1, 1, 0, 0, 1
handle_cmath_1_1_1_1_1_0_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_0_1_0, 1, 1, 1, 1, 1, 0, 1, 0
handle_cmath_1_1_1_1_1_0_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_0_1_1, 1, 1, 1, 1, 1, 0, 1, 1
handle_cmath_1_1_1_1_1_1_0_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_1_0_0, 1, 1, 1, 1, 1, 1, 0, 0
handle_cmath_1_1_1_1_1_1_0_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_1_0_1, 1, 1, 1, 1, 1, 1, 0, 1
handle_cmath_1_1_1_1_1_1_1_0:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_1_1_0, 1, 1, 1, 1, 1, 1, 1, 0
handle_cmath_1_1_1_1_1_1_1_1:
handle_cmath_wrapper handle_cmath_1_1_1_1_1_1_1_1, 1, 1, 1, 1, 1, 1, 1, 1
.align 4
cmath_jump_table:
.long handle_cmath_0_0_0_0_0_0_0_0
.long handle_cmath_0_0_0_0_0_0_0_1
.long handle_cmath_0_0_0_0_0_0_1_0
.long handle_cmath_0_0_0_0_0_0_1_1
.long handle_cmath_0_0_0_0_0_1_0_0
.long handle_cmath_0_0_0_0_0_1_0_1
.long handle_cmath_0_0_0_0_0_1_1_0
.long handle_cmath_0_0_0_0_0_1_1_1
.long handle_cmath_0_0_0_0_1_0_0_0
.long handle_cmath_0_0_0_0_1_0_0_1
.long handle_cmath_0_0_0_0_1_0_1_0
.long handle_cmath_0_0_0_0_1_0_1_1
.long handle_cmath_0_0_0_0_1_1_0_0
.long handle_cmath_0_0_0_0_1_1_0_1
.long handle_cmath_0_0_0_0_1_1_1_0
.long handle_cmath_0_0_0_0_1_1_1_1
.long handle_cmath_0_0_0_1_0_0_0_0
.long handle_cmath_0_0_0_1_0_0_0_1
.long handle_cmath_0_0_0_1_0_0_1_0
.long handle_cmath_0_0_0_1_0_0_1_1
.long handle_cmath_0_0_0_1_0_1_0_0
.long handle_cmath_0_0_0_1_0_1_0_1
.long handle_cmath_0_0_0_1_0_1_1_0
.long handle_cmath_0_0_0_1_0_1_1_1
.long handle_cmath_0_0_0_1_1_0_0_0
.long handle_cmath_0_0_0_1_1_0_0_1
.long handle_cmath_0_0_0_1_1_0_1_0
.long handle_cmath_0_0_0_1_1_0_1_1
.long handle_cmath_0_0_0_1_1_1_0_0
.long handle_cmath_0_0_0_1_1_1_0_1
.long handle_cmath_0_0_0_1_1_1_1_0
.long handle_cmath_0_0_0_1_1_1_1_1
.long handle_cmath_0_0_1_0_0_0_0_0
.long handle_cmath_0_0_1_0_0_0_0_1
.long handle_cmath_0_0_1_0_0_0_1_0
.long handle_cmath_0_0_1_0_0_0_1_1
.long handle_cmath_0_0_1_0_0_1_0_0
.long handle_cmath_0_0_1_0_0_1_0_1
.long handle_cmath_0_0_1_0_0_1_1_0
.long handle_cmath_0_0_1_0_0_1_1_1
.long handle_cmath_0_0_1_0_1_0_0_0
.long handle_cmath_0_0_1_0_1_0_0_1
.long handle_cmath_0_0_1_0_1_0_1_0
.long handle_cmath_0_0_1_0_1_0_1_1
.long handle_cmath_0_0_1_0_1_1_0_0
.long handle_cmath_0_0_1_0_1_1_0_1
.long handle_cmath_0_0_1_0_1_1_1_0
.long handle_cmath_0_0_1_0_1_1_1_1
.long handle_cmath_0_0_1_1_0_0_0_0
.long handle_cmath_0_0_1_1_0_0_0_1
.long handle_cmath_0_0_1_1_0_0_1_0
.long handle_cmath_0_0_1_1_0_0_1_1
.long handle_cmath_0_0_1_1_0_1_0_0
.long handle_cmath_0_0_1_1_0_1_0_1
.long handle_cmath_0_0_1_1_0_1_1_0
.long handle_cmath_0_0_1_1_0_1_1_1
.long handle_cmath_0_0_1_1_1_0_0_0
.long handle_cmath_0_0_1_1_1_0_0_1
.long handle_cmath_0_0_1_1_1_0_1_0
.long handle_cmath_0_0_1_1_1_0_1_1
.long handle_cmath_0_0_1_1_1_1_0_0
.long handle_cmath_0_0_1_1_1_1_0_1
.long handle_cmath_0_0_1_1_1_1_1_0
.long handle_cmath_0_0_1_1_1_1_1_1
.long handle_cmath_0_1_0_0_0_0_0_0
.long handle_cmath_0_1_0_0_0_0_0_1
.long handle_cmath_0_1_0_0_0_0_1_0
.long handle_cmath_0_1_0_0_0_0_1_1
.long handle_cmath_0_1_0_0_0_1_0_0
.long handle_cmath_0_1_0_0_0_1_0_1
.long handle_cmath_0_1_0_0_0_1_1_0
.long handle_cmath_0_1_0_0_0_1_1_1
.long handle_cmath_0_1_0_0_1_0_0_0
.long handle_cmath_0_1_0_0_1_0_0_1
.long handle_cmath_0_1_0_0_1_0_1_0
.long handle_cmath_0_1_0_0_1_0_1_1
.long handle_cmath_0_1_0_0_1_1_0_0
.long handle_cmath_0_1_0_0_1_1_0_1
.long handle_cmath_0_1_0_0_1_1_1_0
.long handle_cmath_0_1_0_0_1_1_1_1
.long handle_cmath_0_1_0_1_0_0_0_0
.long handle_cmath_0_1_0_1_0_0_0_1
.long handle_cmath_0_1_0_1_0_0_1_0
.long handle_cmath_0_1_0_1_0_0_1_1
.long handle_cmath_0_1_0_1_0_1_0_0
.long handle_cmath_0_1_0_1_0_1_0_1
.long handle_cmath_0_1_0_1_0_1_1_0
.long handle_cmath_0_1_0_1_0_1_1_1
.long handle_cmath_0_1_0_1_1_0_0_0
.long handle_cmath_0_1_0_1_1_0_0_1
.long handle_cmath_0_1_0_1_1_0_1_0
.long handle_cmath_0_1_0_1_1_0_1_1
.long handle_cmath_0_1_0_1_1_1_0_0
.long handle_cmath_0_1_0_1_1_1_0_1
.long handle_cmath_0_1_0_1_1_1_1_0
.long handle_cmath_0_1_0_1_1_1_1_1
.long handle_cmath_0_1_1_0_0_0_0_0
.long handle_cmath_0_1_1_0_0_0_0_1
.long handle_cmath_0_1_1_0_0_0_1_0
.long handle_cmath_0_1_1_0_0_0_1_1
.long handle_cmath_0_1_1_0_0_1_0_0
.long handle_cmath_0_1_1_0_0_1_0_1
.long handle_cmath_0_1_1_0_0_1_1_0
.long handle_cmath_0_1_1_0_0_1_1_1
.long handle_cmath_0_1_1_0_1_0_0_0
.long handle_cmath_0_1_1_0_1_0_0_1
.long handle_cmath_0_1_1_0_1_0_1_0
.long handle_cmath_0_1_1_0_1_0_1_1
.long handle_cmath_0_1_1_0_1_1_0_0
.long handle_cmath_0_1_1_0_1_1_0_1
.long handle_cmath_0_1_1_0_1_1_1_0
.long handle_cmath_0_1_1_0_1_1_1_1
.long handle_cmath_0_1_1_1_0_0_0_0
.long handle_cmath_0_1_1_1_0_0_0_1
.long handle_cmath_0_1_1_1_0_0_1_0
.long handle_cmath_0_1_1_1_0_0_1_1
.long handle_cmath_0_1_1_1_0_1_0_0
.long handle_cmath_0_1_1_1_0_1_0_1
.long handle_cmath_0_1_1_1_0_1_1_0
.long handle_cmath_0_1_1_1_0_1_1_1
.long handle_cmath_0_1_1_1_1_0_0_0
.long handle_cmath_0_1_1_1_1_0_0_1
.long handle_cmath_0_1_1_1_1_0_1_0
.long handle_cmath_0_1_1_1_1_0_1_1
.long handle_cmath_0_1_1_1_1_1_0_0
.long handle_cmath_0_1_1_1_1_1_0_1
.long handle_cmath_0_1_1_1_1_1_1_0
.long handle_cmath_0_1_1_1_1_1_1_1
.long handle_cmath_1_0_0_0_0_0_0_0
.long handle_cmath_1_0_0_0_0_0_0_1
.long handle_cmath_1_0_0_0_0_0_1_0
.long handle_cmath_1_0_0_0_0_0_1_1
.long handle_cmath_1_0_0_0_0_1_0_0
.long handle_cmath_1_0_0_0_0_1_0_1
.long handle_cmath_1_0_0_0_0_1_1_0
.long handle_cmath_1_0_0_0_0_1_1_1
.long handle_cmath_1_0_0_0_1_0_0_0
.long handle_cmath_1_0_0_0_1_0_0_1
.long handle_cmath_1_0_0_0_1_0_1_0
.long handle_cmath_1_0_0_0_1_0_1_1
.long handle_cmath_1_0_0_0_1_1_0_0
.long handle_cmath_1_0_0_0_1_1_0_1
.long handle_cmath_1_0_0_0_1_1_1_0
.long handle_cmath_1_0_0_0_1_1_1_1
.long handle_cmath_1_0_0_1_0_0_0_0
.long handle_cmath_1_0_0_1_0_0_0_1
.long handle_cmath_1_0_0_1_0_0_1_0
.long handle_cmath_1_0_0_1_0_0_1_1
.long handle_cmath_1_0_0_1_0_1_0_0
.long handle_cmath_1_0_0_1_0_1_0_1
.long handle_cmath_1_0_0_1_0_1_1_0
.long handle_cmath_1_0_0_1_0_1_1_1
.long handle_cmath_1_0_0_1_1_0_0_0
.long handle_cmath_1_0_0_1_1_0_0_1
.long handle_cmath_1_0_0_1_1_0_1_0
.long handle_cmath_1_0_0_1_1_0_1_1
.long handle_cmath_1_0_0_1_1_1_0_0
.long handle_cmath_1_0_0_1_1_1_0_1
.long handle_cmath_1_0_0_1_1_1_1_0
.long handle_cmath_1_0_0_1_1_1_1_1
.long handle_cmath_1_0_1_0_0_0_0_0
.long handle_cmath_1_0_1_0_0_0_0_1
.long handle_cmath_1_0_1_0_0_0_1_0
.long handle_cmath_1_0_1_0_0_0_1_1
.long handle_cmath_1_0_1_0_0_1_0_0
.long handle_cmath_1_0_1_0_0_1_0_1
.long handle_cmath_1_0_1_0_0_1_1_0
.long handle_cmath_1_0_1_0_0_1_1_1
.long handle_cmath_1_0_1_0_1_0_0_0
.long handle_cmath_1_0_1_0_1_0_0_1
.long handle_cmath_1_0_1_0_1_0_1_0
.long handle_cmath_1_0_1_0_1_0_1_1
.long handle_cmath_1_0_1_0_1_1_0_0
.long handle_cmath_1_0_1_0_1_1_0_1
.long handle_cmath_1_0_1_0_1_1_1_0
.long handle_cmath_1_0_1_0_1_1_1_1
.long handle_cmath_1_0_1_1_0_0_0_0
.long handle_cmath_1_0_1_1_0_0_0_1
.long handle_cmath_1_0_1_1_0_0_1_0
.long handle_cmath_1_0_1_1_0_0_1_1
.long handle_cmath_1_0_1_1_0_1_0_0
.long handle_cmath_1_0_1_1_0_1_0_1
.long handle_cmath_1_0_1_1_0_1_1_0
.long handle_cmath_1_0_1_1_0_1_1_1
.long handle_cmath_1_0_1_1_1_0_0_0
.long handle_cmath_1_0_1_1_1_0_0_1
.long handle_cmath_1_0_1_1_1_0_1_0
.long handle_cmath_1_0_1_1_1_0_1_1
.long handle_cmath_1_0_1_1_1_1_0_0
.long handle_cmath_1_0_1_1_1_1_0_1
.long handle_cmath_1_0_1_1_1_1_1_0
.long handle_cmath_1_0_1_1_1_1_1_1
.long handle_cmath_1_1_0_0_0_0_0_0
.long handle_cmath_1_1_0_0_0_0_0_1
.long handle_cmath_1_1_0_0_0_0_1_0
.long handle_cmath_1_1_0_0_0_0_1_1
.long handle_cmath_1_1_0_0_0_1_0_0
.long handle_cmath_1_1_0_0_0_1_0_1
.long handle_cmath_1_1_0_0_0_1_1_0
.long handle_cmath_1_1_0_0_0_1_1_1
.long handle_cmath_1_1_0_0_1_0_0_0
.long handle_cmath_1_1_0_0_1_0_0_1
.long handle_cmath_1_1_0_0_1_0_1_0
.long handle_cmath_1_1_0_0_1_0_1_1
.long handle_cmath_1_1_0_0_1_1_0_0
.long handle_cmath_1_1_0_0_1_1_0_1
.long handle_cmath_1_1_0_0_1_1_1_0
.long handle_cmath_1_1_0_0_1_1_1_1
.long handle_cmath_1_1_0_1_0_0_0_0
.long handle_cmath_1_1_0_1_0_0_0_1
.long handle_cmath_1_1_0_1_0_0_1_0
.long handle_cmath_1_1_0_1_0_0_1_1
.long handle_cmath_1_1_0_1_0_1_0_0
.long handle_cmath_1_1_0_1_0_1_0_1
.long handle_cmath_1_1_0_1_0_1_1_0
.long handle_cmath_1_1_0_1_0_1_1_1
.long handle_cmath_1_1_0_1_1_0_0_0
.long handle_cmath_1_1_0_1_1_0_0_1
.long handle_cmath_1_1_0_1_1_0_1_0
.long handle_cmath_1_1_0_1_1_0_1_1
.long handle_cmath_1_1_0_1_1_1_0_0
.long handle_cmath_1_1_0_1_1_1_0_1
.long handle_cmath_1_1_0_1_1_1_1_0
.long handle_cmath_1_1_0_1_1_1_1_1
.long handle_cmath_1_1_1_0_0_0_0_0
.long handle_cmath_1_1_1_0_0_0_0_1
.long handle_cmath_1_1_1_0_0_0_1_0
.long handle_cmath_1_1_1_0_0_0_1_1
.long handle_cmath_1_1_1_0_0_1_0_0
.long handle_cmath_1_1_1_0_0_1_0_1
.long handle_cmath_1_1_1_0_0_1_1_0
.long handle_cmath_1_1_1_0_0_1_1_1
.long handle_cmath_1_1_1_0_1_0_0_0
.long handle_cmath_1_1_1_0_1_0_0_1
.long handle_cmath_1_1_1_0_1_0_1_0
.long handle_cmath_1_1_1_0_1_0_1_1
.long handle_cmath_1_1_1_0_1_1_0_0
.long handle_cmath_1_1_1_0_1_1_0_1
.long handle_cmath_1_1_1_0_1_1_1_0
.long handle_cmath_1_1_1_0_1_1_1_1
.long handle_cmath_1_1_1_1_0_0_0_0
.long handle_cmath_1_1_1_1_0_0_0_1
.long handle_cmath_1_1_1_1_0_0_1_0
.long handle_cmath_1_1_1_1_0_0_1_1
.long handle_cmath_1_1_1_1_0_1_0_0
.long handle_cmath_1_1_1_1_0_1_0_1
.long handle_cmath_1_1_1_1_0_1_1_0
.long handle_cmath_1_1_1_1_0_1_1_1
.long handle_cmath_1_1_1_1_1_0_0_0
.long handle_cmath_1_1_1_1_1_0_0_1
.long handle_cmath_1_1_1_1_1_0_1_0
.long handle_cmath_1_1_1_1_1_0_1_1
.long handle_cmath_1_1_1_1_1_1_0_0
.long handle_cmath_1_1_1_1_1_1_0_1
.long handle_cmath_1_1_1_1_1_1_1_0
.long handle_cmath_1_1_1_1_1_1_1_1
.align 4
per_pixel_0_0_0_0_0:
per_pixel_macro per_pixel_0_0_0_0_0, 0, 0, 0, 0, 0
per_pixel_0_0_0_0_1:
per_pixel_macro per_pixel_0_0_0_0_1, 0, 0, 0, 0, 1
per_pixel_0_0_0_1_0:
per_pixel_macro per_pixel_0_0_0_1_0, 0, 0, 0, 1, 0
per_pixel_0_0_0_1_1:
per_pixel_macro per_pixel_0_0_0_1_1, 0, 0, 0, 1, 1
per_pixel_0_0_1_0_0:
per_pixel_macro per_pixel_0_0_1_0_0, 0, 0, 1, 0, 0
per_pixel_0_0_1_0_1:
per_pixel_macro per_pixel_0_0_1_0_1, 0, 0, 1, 0, 1
per_pixel_0_0_1_1_0:
per_pixel_macro per_pixel_0_0_1_1_0, 0, 0, 1, 1, 0
per_pixel_0_0_1_1_1:
per_pixel_macro per_pixel_0_0_1_1_1, 0, 0, 1, 1, 1
per_pixel_0_1_0_0_0:
per_pixel_macro per_pixel_0_1_0_0_0, 0, 1, 0, 0, 0
per_pixel_0_1_0_0_1:
per_pixel_macro per_pixel_0_1_0_0_1, 0, 1, 0, 0, 1
per_pixel_0_1_0_1_0:
per_pixel_macro per_pixel_0_1_0_1_0, 0, 1, 0, 1, 0
per_pixel_0_1_0_1_1:
per_pixel_macro per_pixel_0_1_0_1_1, 0, 1, 0, 1, 1
per_pixel_0_1_1_0_0:
per_pixel_macro per_pixel_0_1_1_0_0, 0, 1, 1, 0, 0
per_pixel_0_1_1_0_1:
per_pixel_macro per_pixel_0_1_1_0_1, 0, 1, 1, 0, 1
per_pixel_0_1_1_1_0:
per_pixel_macro per_pixel_0_1_1_1_0, 0, 1, 1, 1, 0
per_pixel_0_1_1_1_1:
per_pixel_macro per_pixel_0_1_1_1_1, 0, 1, 1, 1, 1
per_pixel_1_0_0_0_0:
per_pixel_macro per_pixel_1_0_0_0_0, 1, 0, 0, 0, 0
per_pixel_1_0_0_0_1:
per_pixel_macro per_pixel_1_0_0_0_1, 1, 0, 0, 0, 1
per_pixel_1_0_0_1_0:
per_pixel_macro per_pixel_1_0_0_1_0, 1, 0, 0, 1, 0
per_pixel_1_0_0_1_1:
per_pixel_macro per_pixel_1_0_0_1_1, 1, 0, 0, 1, 1
per_pixel_1_0_1_0_0:
per_pixel_macro per_pixel_1_0_1_0_0, 1, 0, 1, 0, 0
per_pixel_1_0_1_0_1:
per_pixel_macro per_pixel_1_0_1_0_1, 1, 0, 1, 0, 1
per_pixel_1_0_1_1_0:
per_pixel_macro per_pixel_1_0_1_1_0, 1, 0, 1, 1, 0
per_pixel_1_0_1_1_1:
per_pixel_macro per_pixel_1_0_1_1_1, 1, 0, 1, 1, 1
per_pixel_1_1_0_0_0:
per_pixel_macro per_pixel_1_1_0_0_0, 1, 1, 0, 0, 0
per_pixel_1_1_0_0_1:
per_pixel_macro per_pixel_1_1_0_0_1, 1, 1, 0, 0, 1
per_pixel_1_1_0_1_0:
per_pixel_macro per_pixel_1_1_0_1_0, 1, 1, 0, 1, 0
per_pixel_1_1_0_1_1:
per_pixel_macro per_pixel_1_1_0_1_1, 1, 1, 0, 1, 1
per_pixel_1_1_1_0_0:
per_pixel_macro per_pixel_1_1_1_0_0, 1, 1, 1, 0, 0
per_pixel_1_1_1_0_1:
per_pixel_macro per_pixel_1_1_1_0_1, 1, 1, 1, 0, 1
per_pixel_1_1_1_1_0:
per_pixel_macro per_pixel_1_1_1_1_0, 1, 1, 1, 1, 0
per_pixel_1_1_1_1_1:
per_pixel_macro per_pixel_1_1_1_1_1, 1, 1, 1, 1, 1
.align 4
per_pixel_jump_table:
.long per_pixel_0_0_0_0_0
.long per_pixel_0_0_0_0_1
.long per_pixel_0_0_0_1_0
.long per_pixel_0_0_0_1_1
.long per_pixel_0_0_1_0_0
.long per_pixel_0_0_1_0_1
.long per_pixel_0_0_1_1_0
.long per_pixel_0_0_1_1_1
.long per_pixel_0_1_0_0_0
.long per_pixel_0_1_0_0_1
.long per_pixel_0_1_0_1_0
.long per_pixel_0_1_0_1_1
.long per_pixel_0_1_1_0_0
.long per_pixel_0_1_1_0_1
.long per_pixel_0_1_1_1_0
.long per_pixel_0_1_1_1_1
.long per_pixel_1_0_0_0_0
.long per_pixel_1_0_0_0_1
.long per_pixel_1_0_0_1_0
.long per_pixel_1_0_0_1_1
.long per_pixel_1_0_1_0_0
.long per_pixel_1_0_1_0_1
.long per_pixel_1_0_1_1_0
.long per_pixel_1_0_1_1_1
.long per_pixel_1_1_0_0_0
.long per_pixel_1_1_0_0_1
.long per_pixel_1_1_0_1_0
.long per_pixel_1_1_0_1_1
.long per_pixel_1_1_1_0_0
.long per_pixel_1_1_1_0_1
.long per_pixel_1_1_1_1_0
.long per_pixel_1_1_1_1_1
